const API="https://script.google.com/macros/s/AKfycbw3zpKBt_x7JB_HXgst2F1wb2O_M385SXINZaTs0jhcWQvEjJ5yI4_rGbTcnzP4hpNmtg/exec", EVENT=new Date("2026-10-07T11:00:00-05:00");let chosen=null;
const grid=document.getElementById("grid"),modal=document.getElementById("modal");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function gifts(){try{let r=await fetch(API+"?accion=regalos&t="+Date.now(),{cache:"no-store"}),j=await r.json();if(!j.ok)throw 0;document.getElementById("loading").style.display="none";grid.innerHTML=j.regalos.map((g,i)=>{let x=String(g.estado).toUpperCase()=="APARTADO";return `<article class="gift"><div class="num">${String(i+1).padStart(2,"0")}</div><h3>${esc(g.regalo)}</h3><span class="status ${x?"taken":"avail"}">${x?"♡ Ya fue apartado":"♡ Disponible"}</span><button class="btn" ${x?"disabled":""} data-id="${esc(g.id)}" data-name="${esc(g.regalo)}">${x?"Regalo reservado":"Apartar este regalo"}</button></article>`}).join("");document.querySelectorAll(".gift button:not([disabled])").forEach(b=>b.onclick=()=>openGift(b.dataset.id,b.dataset.name))}catch(e){document.getElementById("loading").textContent="No pudimos cargar la lista. Intenta nuevamente."}}
function openGift(id,name){chosen={id,name};document.getElementById("gtext").textContent=name;document.getElementById("gname").value="";document.getElementById("gmsg").textContent="";document.getElementById("gbtn").disabled=false;modal.classList.remove("hide")}
document.getElementById("x").onclick=()=>modal.classList.add("hide");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hide")};
document.getElementById("gbtn").onclick=async()=>{let n=document.getElementById("gname").value.trim(),b=document.getElementById("gbtn"),m=document.getElementById("gmsg");if(!n){m.textContent="Escribe tu nombre.";return}b.disabled=true;b.textContent="Apartando…";try{let r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({accion:"apartar",id:chosen.id,nombre:n})}),j=await r.json();m.textContent=j.mensaje;if(j.ok){await gifts();setTimeout(()=>modal.classList.add("hide"),1800)}else{b.disabled=false}}catch(e){m.textContent="Problema de conexión. Intenta nuevamente.";b.disabled=false}finally{b.textContent="Sí, quiero apartarlo"}};
document.getElementById("form").onsubmit=async e=>{e.preventDefault();let n=document.getElementById("rname").value.trim(),a=document.querySelector('input[name="resp"]:checked'),b=document.getElementById("rbtn"),m=document.getElementById("rmsg");if(!n||!a)return;b.disabled=true;b.textContent="Guardando…";try{let r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({accion:"asistencia",nombre:n,respuesta:a.value})}),j=await r.json();if(!j.ok)throw 0;m.textContent=a.value.startsWith("SÍ")?"♡ ¡Gracias! Nos encantará celebrar contigo.":"♡ Gracias por hacernos saber.";e.target.reset()}catch(x){m.textContent="No pudimos guardar tu respuesta. Intenta nuevamente."}finally{b.disabled=false;b.textContent="Confirmar asistencia"}};
function clock(){let q=EVENT-new Date();if(q<=0)return;d.textContent=String(Math.floor(q/86400000)).padStart(2,"0");h.textContent=String(Math.floor(q/3600000)%24).padStart(2,"0");m.textContent=String(Math.floor(q/60000)%60).padStart(2,"0");s.textContent=String(Math.floor(q/1000)%60).padStart(2,"0")}clock();setInterval(clock,1000);gifts();setInterval(gifts,30000);
const googleCalendarUrl="https://calendar.google.com/calendar/render?action=TEMPLATE&text="+encodeURIComponent("Baby Shower de Zoe")+"&dates=20261007T160000Z/20261007T170000Z&details="+encodeURIComponent("Baby Shower de Zoe. Invita: Área de Eficiencia y Transformación.")+"&location="+encodeURIComponent("Piso 5 - Edificio sede Banco AV Villas - Gerencia Contact Center");
document.getElementById("googleCalendarBtn").href=googleCalendarUrl;
document.getElementById("calendarFileBtn").addEventListener("click",()=>{
 const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Baby Shower Zoe//ES","CALSCALE:GREGORIAN","BEGIN:VEVENT","UID:baby-shower-zoe-20261007@example.local","DTSTAMP:20260921T000000Z","DTSTART:20261007T160000Z","SUMMARY:Baby Shower de Zoe","LOCATION:Piso 5 - Edificio sede Banco AV Villas - Gerencia Contact Center","DESCRIPTION:Baby Shower de Zoe. Invita: Área de Eficiencia y Transformación.","BEGIN:VALARM","TRIGGER:-P1D","ACTION:DISPLAY","DESCRIPTION:Recordatorio: Baby Shower de Zoe mañana","END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n");
 const blob=new Blob([ics],{type:"text/calendar;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");
 a.href=url;a.download="Baby_Shower_Zoe_7_Octubre.ics";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
});
